"""Add updated_by column to all tables

Revision ID: 339cdd1f1f25
Revises: 1261745219d9
Create Date: 2024-06-11 19:33:12.286857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339cdd1f1f25'
down_revision = '1261745219d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lists_updated_by_users', 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_updated_by_users', 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_updated_by_users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_updated_by_users', type_='foreignkey')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_updated_by_users', type_='foreignkey')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lists_updated_by_users', type_='foreignkey')
        batch_op.drop_column('updated_by')
    # ### end Alembic commands ###
