"""empty message

Revision ID: b61fd97cb4bb
Revises: 4c4244ceb87e
Create Date: 2024-06-06 15:30:42.730541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61fd97cb4bb'
down_revision = '4c4244ceb87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_name_constraint', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name_constraint', type_='unique')

    # ### end Alembic commands ###
